-- Add idea: Night Nurse Hotline for First-Time Parents
-- Original IdeaVault research report (concept inspired by public sources; all
-- text and scoring are IdeaVault's own, demand figures AI-estimated).
-- Run in: Supabase Dashboard → SQL Editor → Run

insert into public.ideas (
  slug, title, tagline, category, signal_tags,
  problem, solution, target_customer, business_model, market_size,
  competition, why_now, demand_signals, keyword, keyword_volume, keyword_growth,
  gtm, mvp_scope, revenue_potential, revenue_tier,
  execution_difficulty, gtm_score, time_to_mvp, startup_costs,
  score_overall, score_opportunity, score_problem, score_feasibility, score_why_now,
  scores, is_flagship, sources, released
) values (
  'night-nurse-hotline-first-time-parents', 'Night Nurse Hotline for First-Time Parents', 'On-call pediatric nurses who read the baby’s tracked data before answering the 3am call', 'Health & Wellness', ARRAY['Perfect Timing', 'Underserved Niche', 'Proven Demand'],
  'Newborn crises cluster in the small hours: fevers, feeding refusals, sleep regressions that feel like emergencies to an exhausted first-time parent. The existing options fail at exactly that moment — insurer nurse lines read from generic scripts, telehealth visits treat the baby as a stranger, and weeks of meticulously logged sleep and feeding data sit unread in a tracking app while the parent panics. The result is defensive ER visits, 3am forum-scrolling, and decisions made on four hours of sleep.', 'A subscription overnight hotline staffed by pediatric nurses and lactation consultants who connect with read-only access to the family’s baby-tracking app. Before the call connects, the consultant sees the child’s age, recent sleep and feeding patterns, and the parent’s stated worry — so answers are grounded in this baby’s actual history: whether the fever warrants the ER, whether to wake the baby to feed, whether a regression is inside normal range.', 'First-time parents of babies 0–6 months in dual-income households already paying for a tracking app (Huckleberry, Napper) and a sleep course — reachable in the sleep-app communities, newborn classes, and the new-parent forums where 3am advice is currently traded for free.', '$79/mo for unlimited overnight access plus a $39 single-session price for crisis-only parents; the anchor is one avoided emergency-room visit paying for most of a year. Natural expansion: daytime milestone check-ins and white-label overnight coverage for pediatric practices.', 'TAM ~$4B (US postpartum care and support services), SAM ~$500M (on-demand infant care guidance for the ~3.6M US births/yr), SOM ~$6M in 3 years at ~6,500 subscribers (AI-est.).',
  'Insurer and hospital nurse advice lines (free but generic, no data context), telehealth pediatrics like Blueberry (visit-based, daytime-oriented), night-nanny agencies ($250+/night, 10–20x the price), and sleep consultants (coaching, not crisis response). Gap: nobody combines overnight availability, clinical credibility, and the family’s own tracked data at a consumer subscription price.', 'Baby-tracking apps made granular sleep/feeding data ubiquitous — yet no clinical service consults it in the panic moment. Telehealth behavior is fully normalized post-2024, pediatric access keeps tightening (longer waits, shrinking after-hours coverage), and premium parents already subscribe to multiple baby services, making an overnight clinical layer an easy add-on rather than a new habit.', 'New-parent communities (r/NewParents, r/beyondthebump, sleep-app groups) run constant overnight crisis threads; night-nurse and newborn-sleep search terms show sustained growth (est.); the paid sleep-consultant market keeps expanding, signaling willingness to pay for infant-sleep help. All figures AI-estimated pending first live signal refresh.', 'night nurse for newborn', 8100, '+180% (est., 12-mo)',
  'Partner with baby-tracking apps for in-app referral placement (they gain a premium answer to “what do I do with this data”); seed the sleep-app communities and new-parent forums with genuinely useful overnight-triage content; add newborn-class and hospital-discharge partnerships; own the exact 3am panic queries with content SEO.', 'Three rotating on-call clinicians covering 10pm–6am, booked through an off-the-shelf scheduler with video calls and a short intake form; read-only tracker access via existing APIs; concierge-serve the first 25 families to learn which questions repeat before building anything custom. Do NOT build an app, daytime coverage, or a clinician marketplace yet.', '~900 subscribers x $79/mo ≈ $71K MRR within 18–24 months at moderate penetration of the annual birth cohort (est.).', '$$$',
  4, 8, '3-5 weeks', '$5K-$12K',
  77, 8, 9, 7, 9,
  '{"problem_severity":{"s":9,"n":"3am infant-health panic is high-stakes decision-making on no sleep"},"community_demand":{"s":9,"n":"Parent forums overflow with overnight crisis threads every single night"},"market_size":{"s":7,"n":"3.6M US births/yr, but each family is addressable for only ~6 months"},"search_growth":{"s":8,"n":"Night-nurse and newborn-sleep queries climbing steadily (est.)"},"why_now":{"s":9,"n":"Tracked-baby data everywhere, telehealth normalized, pediatric access strained"},"competitive_gap":{"s":8,"n":"Advice lines are generic and night nannies cost 10–20x — nobody reads the data"},"monetization_clarity":{"s":9,"n":"One avoided ER visit pays for most of a year — an easy value story"},"revenue_velocity":{"s":7,"n":"High urgency converts fast, but subscribers age out by design at ~6 months"},"solution_feasibility":{"s":8,"n":"Scheduler, video and read-only APIs — all proven components; ops is the work"},"technical_simplicity":{"s":8,"n":"Near-zero novel technology; the product is clinical staffing plus context"},"capital_efficiency":{"s":6,"n":"Overnight clinician coverage is a real fixed cost before subscriber density"},"founder_accessibility":{"s":5,"n":"Needs clinical credibility, malpractice-adjacent liability handling and vetted staff"}}'::jsonb, false, 'https://www.cdc.gov/nchs/fastats/births.htm ; https://www.reddit.com/r/NewParents/ ; https://huckleberrycare.com/', '2026-07-08'
)
on conflict (slug) do nothing;

-- Verify:
select slug, title, category, score_overall, released
from public.ideas where slug = 'night-nurse-hotline-first-time-parents';
